# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oil_hmi_pro.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(809, 571)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 380, 415, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_1_4 = QtWidgets.QLabel(self.frame)
        self.label_1_4.setGeometry(QtCore.QRect(0, 0, 421, 31))
        self.label_1_4.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.label_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_4.setObjectName("label_1_4")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 395, 131))
        self.listWidget.setObjectName("listWidget")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 60, 251, 311))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(134, 140, 102, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(14, 140, 102, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(14, 200, 221, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(14, 90, 102, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_1_2 = QtWidgets.QLabel(self.frame_2)
        self.label_1_2.setGeometry(QtCore.QRect(0, 0, 261, 31))
        self.label_1_2.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.label_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_2.setObjectName("label_1_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(134, 90, 102, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox2.setGeometry(QtCore.QRect(134, 40, 102, 40))
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox3 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox3.setGeometry(QtCore.QRect(14, 40, 102, 40))
        self.comboBox3.setStyleSheet("")
        self.comboBox3.setObjectName("comboBox3")
        self.comboBox3.addItem("")
        self.comboBox3.addItem("")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(440, 60, 361, 501))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.backHomeButton = QtWidgets.QPushButton(self.frame_3)
        self.backHomeButton.setGeometry(QtCore.QRect(120, 450, 96, 40))
        self.backHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.backHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.backHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backHomeButton.setObjectName("backHomeButton")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(17, 374, 81, 32))
        self.label_33.setObjectName("label_33")
        self.stopButton = QtWidgets.QPushButton(self.frame_3)
        self.stopButton.setGeometry(QtCore.QRect(230, 450, 120, 40))
        self.stopButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stopButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stopButton.setFont(font)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopButton.setObjectName("stopButton")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(107, 377, 234, 28))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(99)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(8)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 339, 338))
        self.tabWidget.setMaximumSize(QtCore.QSize(339, 16777215))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(10, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1_2 = QtWidgets.QWidget()
        self.tab1_2.setObjectName("tab1_2")
        self.radDegButton_1 = QtWidgets.QPushButton(self.tab1_2)
        self.radDegButton_1.setGeometry(QtCore.QRect(67, 269, 69, 29))
        self.radDegButton_1.setObjectName("radDegButton_1")
        self.label_7 = QtWidgets.QLabel(self.tab1_2)
        self.label_7.setGeometry(QtCore.QRect(4, 229, 143, 32))
        self.label_7.setObjectName("label_7")
        self.pushButton3_2 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton3_2.setGeometry(QtCore.QRect(246, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_2.setFont(font)
        self.pushButton3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_2.setObjectName("pushButton3_2")
        self.label_step = QtWidgets.QLabel(self.tab1_2)
        self.label_step.setGeometry(QtCore.QRect(172, 266, 41, 32))
        self.label_step.setObjectName("label_step")
        self.pushButton5_1 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton5_1.setGeometry(QtCore.QRect(150, 154, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_1.setFont(font)
        self.pushButton5_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_1.setObjectName("pushButton5_1")
        self.pushButton6_2 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton6_2.setGeometry(QtCore.QRect(246, 192, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_2.setFont(font)
        self.pushButton6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_2.setObjectName("pushButton6_2")
        self.label_5 = QtWidgets.QLabel(self.tab1_2)
        self.label_5.setGeometry(QtCore.QRect(4, 153, 143, 32))
        self.label_5.setObjectName("label_5")
        self.pushButton4_2 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton4_2.setGeometry(QtCore.QRect(246, 116, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_2.setFont(font)
        self.pushButton4_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_2.setObjectName("pushButton4_2")
        self.comboBox = QtWidgets.QComboBox(self.tab1_2)
        self.comboBox.setGeometry(QtCore.QRect(212, 268, 85, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton5_2 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton5_2.setGeometry(QtCore.QRect(246, 154, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_2.setFont(font)
        self.pushButton5_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_2.setObjectName("pushButton5_2")
        self.pushButton6_1 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton6_1.setGeometry(QtCore.QRect(150, 192, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_1.setFont(font)
        self.pushButton6_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_1.setObjectName("pushButton6_1")
        self.pushButton1_1 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton1_1.setGeometry(QtCore.QRect(150, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_1.setFont(font)
        self.pushButton1_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.pushButton7_1 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton7_1.setGeometry(QtCore.QRect(150, 230, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_1.setFont(font)
        self.pushButton7_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_1.setObjectName("pushButton7_1")
        self.label_6 = QtWidgets.QLabel(self.tab1_2)
        self.label_6.setGeometry(QtCore.QRect(4, 191, 143, 32))
        self.label_6.setObjectName("label_6")
        self.pushButton1_2 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton1_2.setGeometry(QtCore.QRect(246, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_2.setFont(font)
        self.pushButton1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.pushButton7_2 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton7_2.setGeometry(QtCore.QRect(246, 230, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_2.setFont(font)
        self.pushButton7_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_2.setObjectName("pushButton7_2")
        self.label_4 = QtWidgets.QLabel(self.tab1_2)
        self.label_4.setGeometry(QtCore.QRect(4, 115, 143, 32))
        self.label_4.setObjectName("label_4")
        self.pushButton2_1 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton2_1.setGeometry(QtCore.QRect(150, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_1.setFont(font)
        self.pushButton2_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.pushButton2_2 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton2_2.setGeometry(QtCore.QRect(246, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_2.setFont(font)
        self.pushButton2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.pushButton4_1 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton4_1.setGeometry(QtCore.QRect(150, 116, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_1.setFont(font)
        self.pushButton4_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_1.setObjectName("pushButton4_1")
        self.label_2 = QtWidgets.QLabel(self.tab1_2)
        self.label_2.setGeometry(QtCore.QRect(4, 39, 143, 32))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab1_2)
        self.label_3.setGeometry(QtCore.QRect(4, 77, 143, 32))
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(self.tab1_2)
        self.label_1.setGeometry(QtCore.QRect(4, 1, 143, 32))
        self.label_1.setObjectName("label_1")
        self.pushButton3_1 = QtWidgets.QPushButton(self.tab1_2)
        self.pushButton3_1.setGeometry(QtCore.QRect(150, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_1.setFont(font)
        self.pushButton3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_1.setObjectName("pushButton3_1")
        self.label_unit = QtWidgets.QLabel(self.tab1_2)
        self.label_unit.setGeometry(QtCore.QRect(30, 266, 41, 32))
        self.label_unit.setObjectName("label_unit")
        self.tabWidget.addTab(self.tab1_2, "")
        self.tab2_2 = QtWidgets.QWidget()
        self.tab2_2.setObjectName("tab2_2")
        self.pushButton7_3 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton7_3.setGeometry(QtCore.QRect(150, 235, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_3.setFont(font)
        self.pushButton7_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_3.setObjectName("pushButton7_3")
        self.pushButton5_3 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton5_3.setGeometry(QtCore.QRect(150, 156, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_3.setFont(font)
        self.pushButton5_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_3.setObjectName("pushButton5_3")
        self.label_24 = QtWidgets.QLabel(self.tab2_2)
        self.label_24.setGeometry(QtCore.QRect(30, 269, 41, 32))
        self.label_24.setObjectName("label_24")
        self.label_step3_2 = QtWidgets.QLabel(self.tab2_2)
        self.label_step3_2.setGeometry(QtCore.QRect(172, 269, 41, 32))
        self.label_step3_2.setObjectName("label_step3_2")
        self.pushButton5_4 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton5_4.setGeometry(QtCore.QRect(246, 156, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_4.setFont(font)
        self.pushButton5_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_4.setObjectName("pushButton5_4")
        self.pushButton2_4 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton2_4.setGeometry(QtCore.QRect(246, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_4.setFont(font)
        self.pushButton2_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_4.setObjectName("pushButton2_4")
        self.pushButton6_4 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton6_4.setGeometry(QtCore.QRect(246, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_4.setFont(font)
        self.pushButton6_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_4.setObjectName("pushButton6_4")
        self.pushButton7_4 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton7_4.setGeometry(QtCore.QRect(246, 235, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_4.setFont(font)
        self.pushButton7_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_4.setObjectName("pushButton7_4")
        self.pushButton6_3 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton6_3.setGeometry(QtCore.QRect(150, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_3.setFont(font)
        self.pushButton6_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_3.setObjectName("pushButton6_3")
        self.radDegButton_2 = QtWidgets.QPushButton(self.tab2_2)
        self.radDegButton_2.setGeometry(QtCore.QRect(67, 272, 69, 29))
        self.radDegButton_2.setObjectName("radDegButton_2")
        self.pushButton1_3 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton1_3.setGeometry(QtCore.QRect(150, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_3.setFont(font)
        self.pushButton1_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.pushButton1_4 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton1_4.setGeometry(QtCore.QRect(246, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_4.setFont(font)
        self.pushButton1_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.label_9 = QtWidgets.QLabel(self.tab2_2)
        self.label_9.setGeometry(QtCore.QRect(4, 1, 143, 32))
        self.label_9.setObjectName("label_9")
        self.comboBox_rpy = QtWidgets.QComboBox(self.tab2_2)
        self.comboBox_rpy.setGeometry(QtCore.QRect(212, 271, 85, 30))
        self.comboBox_rpy.setObjectName("comboBox_rpy")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab2_2)
        self.label_11.setGeometry(QtCore.QRect(4, 77, 143, 32))
        self.label_11.setObjectName("label_11")
        self.pushButton3_3 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton3_3.setGeometry(QtCore.QRect(150, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_3.setFont(font)
        self.pushButton3_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_3.setObjectName("pushButton3_3")
        self.pushButton3_4 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton3_4.setGeometry(QtCore.QRect(246, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_4.setFont(font)
        self.pushButton3_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_4.setObjectName("pushButton3_4")
        self.label_12 = QtWidgets.QLabel(self.tab2_2)
        self.label_12.setGeometry(QtCore.QRect(4, 156, 143, 32))
        self.label_12.setObjectName("label_12")
        self.pushButton2_3 = QtWidgets.QPushButton(self.tab2_2)
        self.pushButton2_3.setGeometry(QtCore.QRect(150, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_3.setFont(font)
        self.pushButton2_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_3.setObjectName("pushButton2_3")
        self.label_10 = QtWidgets.QLabel(self.tab2_2)
        self.label_10.setGeometry(QtCore.QRect(4, 39, 143, 32))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.tab2_2)
        self.label_13.setGeometry(QtCore.QRect(4, 194, 143, 32))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab2_2)
        self.label_14.setGeometry(QtCore.QRect(4, 232, 143, 32))
        self.label_14.setObjectName("label_14")
        self.label_step2_2 = QtWidgets.QLabel(self.tab2_2)
        self.label_step2_2.setGeometry(QtCore.QRect(172, 113, 41, 32))
        self.label_step2_2.setObjectName("label_step2_2")
        self.label_32 = QtWidgets.QLabel(self.tab2_2)
        self.label_32.setGeometry(QtCore.QRect(30, 113, 41, 32))
        self.label_32.setObjectName("label_32")
        self.mCmButton_1 = QtWidgets.QPushButton(self.tab2_2)
        self.mCmButton_1.setGeometry(QtCore.QRect(67, 116, 69, 29))
        self.mCmButton_1.setObjectName("mCmButton_1")
        self.comboBox_xyz = QtWidgets.QComboBox(self.tab2_2)
        self.comboBox_xyz.setGeometry(QtCore.QRect(212, 115, 85, 30))
        self.comboBox_xyz.setObjectName("comboBox_xyz")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.line_2 = QtWidgets.QFrame(self.tab2_2)
        self.line_2.setGeometry(QtCore.QRect(32, 143, 265, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tab2_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox_ee = QtWidgets.QComboBox(self.tab)
        self.comboBox_ee.setGeometry(QtCore.QRect(165, 50, 85, 30))
        self.comboBox_ee.setObjectName("comboBox_ee")
        self.comboBox_ee.addItem("")
        self.comboBox_ee.addItem("")
        self.comboBox_ee.addItem("")
        self.comboBox_ee.addItem("")
        self.comboBox_ee.addItem("")
        self.label_step2_3 = QtWidgets.QLabel(self.tab)
        self.label_step2_3.setGeometry(QtCore.QRect(70, 48, 81, 32))
        self.label_step2_3.setObjectName("label_step2_3")
        self.MoveEEZ_Button2 = QtWidgets.QPushButton(self.tab)
        self.MoveEEZ_Button2.setGeometry(QtCore.QRect(166, 160, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.MoveEEZ_Button2.setFont(font)
        self.MoveEEZ_Button2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MoveEEZ_Button2.setObjectName("MoveEEZ_Button2")
        self.MoveEEZ_Button1 = QtWidgets.QPushButton(self.tab)
        self.MoveEEZ_Button1.setGeometry(QtCore.QRect(70, 160, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.MoveEEZ_Button1.setFont(font)
        self.MoveEEZ_Button1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MoveEEZ_Button1.setObjectName("MoveEEZ_Button1")
        self.label_step2_4 = QtWidgets.QLabel(self.tab)
        self.label_step2_4.setGeometry(QtCore.QRect(70, 90, 91, 32))
        self.label_step2_4.setObjectName("label_step2_4")
        self.comboBox_ee_scale = QtWidgets.QComboBox(self.tab)
        self.comboBox_ee_scale.setGeometry(QtCore.QRect(165, 90, 85, 30))
        self.comboBox_ee_scale.setObjectName("comboBox_ee_scale")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.comboBox_ee_scale.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.setHomeButton = QtWidgets.QPushButton(self.frame_3)
        self.setHomeButton.setGeometry(QtCore.QRect(10, 403, 96, 40))
        self.setHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.setHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.setHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setHomeButton.setObjectName("setHomeButton")
        self.saveButton = QtWidgets.QPushButton(self.frame_3)
        self.saveButton.setGeometry(QtCore.QRect(10, 450, 96, 40))
        self.saveButton.setMinimumSize(QtCore.QSize(96, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(120, 120))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setObjectName("saveButton")
        self.powerButton = QtWidgets.QPushButton(self.frame_3)
        self.powerButton.setGeometry(QtCore.QRect(230, 403, 120, 40))
        self.powerButton.setMinimumSize(QtCore.QSize(30, 30))
        self.powerButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.powerButton.setFont(font)
        self.powerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerButton.setObjectName("powerButton")
        self.resetButton = QtWidgets.QPushButton(self.frame_3)
        self.resetButton.setGeometry(QtCore.QRect(120, 403, 96, 40))
        self.resetButton.setMinimumSize(QtCore.QSize(96, 30))
        self.resetButton.setMaximumSize(QtCore.QSize(120, 120))
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName("resetButton")
        self.label_1_5 = QtWidgets.QLabel(self.frame_3)
        self.label_1_5.setGeometry(QtCore.QRect(0, 0, 361, 31))
        self.label_1_5.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.label_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_5.setObjectName("label_1_5")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(274, 60, 151, 311))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_1_3 = QtWidgets.QLabel(self.frame_4)
        self.label_1_3.setGeometry(QtCore.QRect(0, 0, 151, 31))
        self.label_1_3.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.label_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_3.setObjectName("label_1_3")
        self.lift_up_button = QtWidgets.QPushButton(self.frame_4)
        self.lift_up_button.setGeometry(QtCore.QRect(20, 71, 51, 31))
        self.lift_up_button.setObjectName("lift_up_button")
        self.lift_down_button = QtWidgets.QPushButton(self.frame_4)
        self.lift_down_button.setGeometry(QtCore.QRect(82, 71, 51, 31))
        self.lift_down_button.setObjectName("lift_down_button")
        self.comboBox_lift_step = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_lift_step.setGeometry(QtCore.QRect(60, 41, 74, 27))
        self.comboBox_lift_step.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_lift_step.setObjectName("comboBox_lift_step")
        self.comboBox_lift_step.addItem("")
        self.comboBox_lift_step.addItem("")
        self.comboBox_lift_step.addItem("")
        self.label_1_6 = QtWidgets.QLabel(self.frame_4)
        self.label_1_6.setGeometry(QtCore.QRect(20, 28, 31, 51))
        self.label_1_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_6.setStyleSheet("")
        self.label_1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_6.setObjectName("label_1_6")
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setGeometry(QtCore.QRect(90, 177, 44, 27))
        self.textEdit.setObjectName("textEdit")
        self.label_1_7 = QtWidgets.QLabel(self.frame_4)
        self.label_1_7.setGeometry(QtCore.QRect(20, 178, 61, 21))
        self.label_1_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_7.setStyleSheet("")
        self.label_1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_7.setObjectName("label_1_7")
        self.lift_back_home_button = QtWidgets.QPushButton(self.frame_4)
        self.lift_back_home_button.setGeometry(QtCore.QRect(20, 108, 51, 31))
        self.lift_back_home_button.setObjectName("lift_back_home_button")
        self.label_1_8 = QtWidgets.QLabel(self.frame_4)
        self.label_1_8.setGeometry(QtCore.QRect(20, 147, 61, 21))
        self.label_1_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_8.setStyleSheet("")
        self.label_1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_8.setObjectName("label_1_8")
        self.label_lift_pose = QtWidgets.QLabel(self.frame_4)
        self.label_lift_pose.setGeometry(QtCore.QRect(83, 148, 56, 21))
        self.label_lift_pose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_lift_pose.setStyleSheet("")
        self.label_lift_pose.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lift_pose.setObjectName("label_lift_pose")
        self.lift_stop_button = QtWidgets.QPushButton(self.frame_4)
        self.lift_stop_button.setGeometry(QtCore.QRect(82, 110, 51, 31))
        self.lift_stop_button.setObjectName("lift_stop_button")
        self.textEdit_lift_speed = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_lift_speed.setGeometry(QtCore.QRect(90, 244, 44, 27))
        self.textEdit_lift_speed.setObjectName("textEdit_lift_speed")
        self.label_1_9 = QtWidgets.QLabel(self.frame_4)
        self.label_1_9.setGeometry(QtCore.QRect(20, 245, 61, 21))
        self.label_1_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_9.setStyleSheet("")
        self.label_1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_9.setObjectName("label_1_9")
        self.lift_speed_button = QtWidgets.QPushButton(self.frame_4)
        self.lift_speed_button.setGeometry(QtCore.QRect(20, 275, 114, 31))
        self.lift_speed_button.setObjectName("lift_speed_button")
        self.lift_pose_button = QtWidgets.QPushButton(self.frame_4)
        self.lift_pose_button.setGeometry(QtCore.QRect(20, 208, 114, 31))
        self.lift_pose_button.setObjectName("lift_pose_button")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(3)
        self.comboBox_rpy.setCurrentIndex(3)
        self.comboBox_xyz.setCurrentIndex(3)
        self.comboBox_ee.setCurrentIndex(0)
        self.comboBox_ee_scale.setCurrentIndex(6)
        self.powerButton.pressed.connect(Form.power)
        self.saveButton.pressed.connect(Form.save_state)
        self.horizontalSlider.valueChanged['int'].connect(Form.slide_moved)
        self.resetButton.pressed.connect(Form.reset_arm)
        self.setHomeButton.pressed.connect(Form.set_home)
        self.backHomeButton.pressed.connect(Form.back_home)
        self.stopButton.released.connect(Form.emergency_stop)
        self.pushButton1_1.pressed.connect(Form.joint1_minus)
        self.pushButton1_1.released.connect(Form.joint1_minus_done)
        self.pushButton1_2.pressed.connect(Form.joint1_plus)
        self.pushButton1_2.released.connect(Form.joint1_plus_done)
        self.pushButton2_1.pressed.connect(Form.joint2_minus)
        self.pushButton2_1.released.connect(Form.joint2_minus_done)
        self.pushButton2_2.pressed.connect(Form.joint2_plus)
        self.pushButton2_2.released.connect(Form.joint2_plus_done)
        self.pushButton3_1.pressed.connect(Form.joint3_minus)
        self.pushButton3_1.released.connect(Form.joint3_minus_done)
        self.pushButton3_2.pressed.connect(Form.joint3_plus)
        self.pushButton3_2.released.connect(Form.joint3_plus_done)
        self.pushButton4_1.pressed.connect(Form.joint4_minus)
        self.pushButton4_1.released.connect(Form.joint4_minus_done)
        self.pushButton4_2.pressed.connect(Form.joint4_plus)
        self.pushButton4_2.released.connect(Form.joint4_plus_done)
        self.pushButton5_1.pressed.connect(Form.joint5_minus)
        self.pushButton5_1.released.connect(Form.joint5_minus_done)
        self.pushButton5_2.pressed.connect(Form.joint5_plus)
        self.pushButton5_2.released.connect(Form.joint5_plus_done)
        self.pushButton6_1.pressed.connect(Form.joint6_minus)
        self.pushButton6_1.released.connect(Form.joint6_minus_done)
        self.pushButton6_2.pressed.connect(Form.joint6_plus)
        self.pushButton6_2.released.connect(Form.joint6_plus_done)
        self.pushButton7_1.pressed.connect(Form.joint7_minus)
        self.pushButton7_1.released.connect(Form.joint7_minus_done)
        self.pushButton7_2.pressed.connect(Form.joint7_plus)
        self.pushButton7_2.released.connect(Form.joint7_plus_done)
        self.pushButton1_3.pressed.connect(Form.x_minus)
        self.pushButton1_4.pressed.connect(Form.x_plus)
        self.pushButton2_3.pressed.connect(Form.y_minus)
        self.pushButton2_4.pressed.connect(Form.y_plus)
        self.pushButton3_3.pressed.connect(Form.z_minus)
        self.pushButton3_4.pressed.connect(Form.z_plus)
        self.pushButton5_3.pressed.connect(Form.roll_minus)
        self.pushButton5_4.pressed.connect(Form.roll_plus)
        self.pushButton6_3.pressed.connect(Form.pitch_minus)
        self.pushButton6_4.pressed.connect(Form.pitch_plus)
        self.pushButton7_3.pressed.connect(Form.yaw_minus)
        self.pushButton7_4.pressed.connect(Form.yaw_plus)
        self.comboBox_xyz.currentIndexChanged['int'].connect(Form.movexyz_step_change)
        self.comboBox_rpy.currentIndexChanged['int'].connect(Form.moverpy_step_change)
        self.comboBox.currentIndexChanged['int'].connect(Form.movej_step_change)
        self.radDegButton_1.pressed.connect(Form.movej_rad_deg)
        self.radDegButton_2.pressed.connect(Form.movel_rad_deg)
        self.mCmButton_1.pressed.connect(Form.movel_m_cm)
        self.lift_back_home_button.pressed.connect(Form.lift_back_home)
        self.lift_pose_button.pressed.connect(Form.lift_pose_modify)
        self.MoveEEZ_Button1.pressed.connect(Form.move_e_backward)
        self.MoveEEZ_Button2.pressed.connect(Form.move_e_forward)
        self.comboBox_ee_scale.currentTextChanged['QString'].connect(Form.move_ee_scale_changed)
        self.lift_stop_button.pressed.connect(Form.lift_stop)
        self.lift_up_button.pressed.connect(Form.lift_up)
        self.lift_down_button.pressed.connect(Form.lift_down)
        self.lift_speed_button.pressed.connect(Form.lift_speed_modify)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Oil HMI"))
        self.label.setText(_translate("Form", "模拟对接试验"))
        self.label_1_4.setText(_translate("Form", "状态信息栏"))
        self.pushButton_7.setText(_translate("Form", "退出对接"))
        self.pushButton_5.setText(_translate("Form", "执行对接"))
        self.pushButton_6.setText(_translate("Form", "退出到对接通道入口"))
        self.pushButton_3.setText(_translate("Form", "初始化"))
        self.label_1_2.setText(_translate("Form", "对接控制"))
        self.pushButton_4.setText(_translate("Form", "开始"))
        self.comboBox2.setItemText(0, _translate("Form", "1号目标点"))
        self.comboBox2.setItemText(1, _translate("Form", "2号目标点"))
        self.comboBox3.setItemText(0, _translate("Form", "阶段模式"))
        self.comboBox3.setItemText(1, _translate("Form", "连续模式"))
        self.backHomeButton.setText(_translate("Form", "Back Home"))
        self.label_33.setText(_translate("Form", "Speed 50%"))
        self.stopButton.setText(_translate("Form", "Emergency"))
        self.radDegButton_1.setText(_translate("Form", "deg"))
        self.label_7.setText(_translate("Form", "Joint7 ( 0.000 rad )"))
        self.pushButton3_2.setText(_translate("Form", "+"))
        self.label_step.setText(_translate("Form", "Step:"))
        self.pushButton5_1.setText(_translate("Form", "-"))
        self.pushButton6_2.setText(_translate("Form", "+"))
        self.label_5.setText(_translate("Form", "Joint5 ( 0.000 rad )"))
        self.pushButton4_2.setText(_translate("Form", "+"))
        self.comboBox.setItemText(0, _translate("Form", "90.0 deg"))
        self.comboBox.setItemText(1, _translate("Form", "60.0 deg"))
        self.comboBox.setItemText(2, _translate("Form", "30.0 deg"))
        self.comboBox.setItemText(3, _translate("Form", "10.0 deg"))
        self.comboBox.setItemText(4, _translate("Form", "5.00 deg"))
        self.comboBox.setItemText(5, _translate("Form", "1.00 deg"))
        self.comboBox.setItemText(6, _translate("Form", "0.50 deg"))
        self.comboBox.setItemText(7, _translate("Form", "0.25 deg"))
        self.comboBox.setItemText(8, _translate("Form", "0.10 deg"))
        self.comboBox.setItemText(9, _translate("Form", "0.05 deg"))
        self.comboBox.setItemText(10, _translate("Form", "1.60 rad"))
        self.comboBox.setItemText(11, _translate("Form", "0.80 rad"))
        self.comboBox.setItemText(12, _translate("Form", "0.40 rad"))
        self.comboBox.setItemText(13, _translate("Form", "0.20 rad"))
        self.comboBox.setItemText(14, _translate("Form", "0.10 rad"))
        self.comboBox.setItemText(15, _translate("Form", "0.05 rad"))
        self.comboBox.setItemText(16, _translate("Form", "0.02 rad"))
        self.comboBox.setItemText(17, _translate("Form", "0.01 rad"))
        self.pushButton5_2.setText(_translate("Form", "+"))
        self.pushButton6_1.setText(_translate("Form", "-"))
        self.pushButton1_1.setText(_translate("Form", "-"))
        self.pushButton7_1.setText(_translate("Form", "-"))
        self.label_6.setText(_translate("Form", "Joint6 ( 0.000 rad )"))
        self.pushButton1_2.setText(_translate("Form", "+"))
        self.pushButton7_2.setText(_translate("Form", "+"))
        self.label_4.setText(_translate("Form", "Joint4 ( 0.000 rad )"))
        self.pushButton2_1.setText(_translate("Form", "-"))
        self.pushButton2_2.setText(_translate("Form", "+"))
        self.pushButton4_1.setText(_translate("Form", "-"))
        self.label_2.setText(_translate("Form", "Joint2 ( 0.000 rad )"))
        self.label_3.setText(_translate("Form", "Joint3 ( 0.000 rad )"))
        self.label_1.setText(_translate("Form", "Joint1 ( 0.000 rad )"))
        self.pushButton3_1.setText(_translate("Form", "-"))
        self.label_unit.setText(_translate("Form", "Unit:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1_2), _translate("Form", "         MoveJ        "))
        self.pushButton7_3.setText(_translate("Form", "-"))
        self.pushButton5_3.setText(_translate("Form", "-"))
        self.label_24.setText(_translate("Form", "Unit:"))
        self.label_step3_2.setText(_translate("Form", "Step:"))
        self.pushButton5_4.setText(_translate("Form", "+"))
        self.pushButton2_4.setText(_translate("Form", "+"))
        self.pushButton6_4.setText(_translate("Form", "+"))
        self.pushButton7_4.setText(_translate("Form", "+"))
        self.pushButton6_3.setText(_translate("Form", "-"))
        self.radDegButton_2.setText(_translate("Form", "deg"))
        self.pushButton1_3.setText(_translate("Form", "-"))
        self.pushButton1_4.setText(_translate("Form", "+"))
        self.label_9.setText(_translate("Form", "Pose X ( 0.000 m )"))
        self.comboBox_rpy.setItemText(0, _translate("Form", "60.0 deg"))
        self.comboBox_rpy.setItemText(1, _translate("Form", "30.0 deg"))
        self.comboBox_rpy.setItemText(2, _translate("Form", "10.0 deg"))
        self.comboBox_rpy.setItemText(3, _translate("Form", "5.00 deg"))
        self.comboBox_rpy.setItemText(4, _translate("Form", "1.00 deg"))
        self.comboBox_rpy.setItemText(5, _translate("Form", "0.50 deg"))
        self.comboBox_rpy.setItemText(6, _translate("Form", "0.10 deg"))
        self.comboBox_rpy.setItemText(7, _translate("Form", "0.80 rad"))
        self.comboBox_rpy.setItemText(8, _translate("Form", "0.40 rad"))
        self.comboBox_rpy.setItemText(9, _translate("Form", "0.20 rad"))
        self.comboBox_rpy.setItemText(10, _translate("Form", "0.10 rad"))
        self.comboBox_rpy.setItemText(11, _translate("Form", "0.05 rad"))
        self.comboBox_rpy.setItemText(12, _translate("Form", "0.02 rad"))
        self.label_11.setText(_translate("Form", "Pose Z ( 0.000 m )"))
        self.pushButton3_3.setText(_translate("Form", "-"))
        self.pushButton3_4.setText(_translate("Form", "+"))
        self.label_12.setText(_translate("Form", "Pose R ( 0.000 rad )"))
        self.pushButton2_3.setText(_translate("Form", "-"))
        self.label_10.setText(_translate("Form", "Pose Y ( 0.000 m )"))
        self.label_13.setText(_translate("Form", "Pose P ( 0.000 rad )"))
        self.label_14.setText(_translate("Form", "Pose Y ( 0.000 rad )"))
        self.label_step2_2.setText(_translate("Form", "Step:"))
        self.label_32.setText(_translate("Form", "Unit:"))
        self.mCmButton_1.setText(_translate("Form", "m"))
        self.comboBox_xyz.setItemText(0, _translate("Form", "0.20 m"))
        self.comboBox_xyz.setItemText(1, _translate("Form", "0.15 m"))
        self.comboBox_xyz.setItemText(2, _translate("Form", "0.10 m"))
        self.comboBox_xyz.setItemText(3, _translate("Form", "0.05 m"))
        self.comboBox_xyz.setItemText(4, _translate("Form", "0.02 m"))
        self.comboBox_xyz.setItemText(5, _translate("Form", "0.01 m"))
        self.comboBox_xyz.setItemText(6, _translate("Form", "20.0 cm"))
        self.comboBox_xyz.setItemText(7, _translate("Form", "15.0 cm"))
        self.comboBox_xyz.setItemText(8, _translate("Form", "10.0 cm"))
        self.comboBox_xyz.setItemText(9, _translate("Form", "5.00 cm"))
        self.comboBox_xyz.setItemText(10, _translate("Form", "2.00 cm"))
        self.comboBox_xyz.setItemText(11, _translate("Form", "1.00 cm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2_2), _translate("Form", "        MoveL      "))
        self.comboBox_ee.setItemText(0, _translate("Form", "0.01 m"))
        self.comboBox_ee.setItemText(1, _translate("Form", "0.02 m"))
        self.comboBox_ee.setItemText(2, _translate("Form", "0.05 m"))
        self.comboBox_ee.setItemText(3, _translate("Form", "0.10 m"))
        self.comboBox_ee.setItemText(4, _translate("Form", "0.20 m"))
        self.label_step2_3.setText(_translate("Form", "Move Step:"))
        self.MoveEEZ_Button2.setText(_translate("Form", "+"))
        self.MoveEEZ_Button1.setText(_translate("Form", "-"))
        self.label_step2_4.setText(_translate("Form", "Speed Scale:"))
        self.comboBox_ee_scale.setItemText(0, _translate("Form", "0.9"))
        self.comboBox_ee_scale.setItemText(1, _translate("Form", "0.8"))
        self.comboBox_ee_scale.setItemText(2, _translate("Form", "0.7"))
        self.comboBox_ee_scale.setItemText(3, _translate("Form", "0.6"))
        self.comboBox_ee_scale.setItemText(4, _translate("Form", "0.5"))
        self.comboBox_ee_scale.setItemText(5, _translate("Form", "0.4"))
        self.comboBox_ee_scale.setItemText(6, _translate("Form", "0.3"))
        self.comboBox_ee_scale.setItemText(7, _translate("Form", "0.2"))
        self.comboBox_ee_scale.setItemText(8, _translate("Form", "0.1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "        MoveE      "))
        self.setHomeButton.setText(_translate("Form", "Set Home"))
        self.saveButton.setText(_translate("Form", "Save States"))
        self.powerButton.setText(_translate("Form", "Power OFF"))
        self.resetButton.setText(_translate("Form", "Reset Arm"))
        self.label_1_5.setText(_translate("Form", "机械臂控制"))
        self.label_1_3.setText(_translate("Form", "升降机构控制"))
        self.lift_up_button.setText(_translate("Form", "上升"))
        self.lift_down_button.setText(_translate("Form", "下降"))
        self.comboBox_lift_step.setItemText(0, _translate("Form", "50 mm"))
        self.comboBox_lift_step.setItemText(1, _translate("Form", "20 mm"))
        self.comboBox_lift_step.setItemText(2, _translate("Form", "10 mm"))
        self.label_1_6.setText(_translate("Form", "步进"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0000</p></body></html>"))
        self.label_1_7.setText(_translate("Form", "目标位置"))
        self.lift_back_home_button.setText(_translate("Form", "回零"))
        self.label_1_8.setText(_translate("Form", "当前位置"))
        self.label_lift_pose.setText(_translate("Form", "0000"))
        self.lift_stop_button.setText(_translate("Form", "急停"))
        self.textEdit_lift_speed.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0010</p></body></html>"))
        self.label_1_9.setText(_translate("Form", "目标速度"))
        self.lift_speed_button.setText(_translate("Form", "修改速度 (mm)"))
        self.lift_pose_button.setText(_translate("Form", "修改位置 (mm)"))

